import Head from "next/head";
import styles from "./Home.module.css";

export const Home = () => {
  const handleSubmit = (event) => {
    event.preventDefault();
    const form = event.target;
    const input = form.elements[0];
    const value = input.value.trim();
    if (value) {
      window.location.href = `/${value}`;
    }
  };

  return (
    <>
      <Head>
        <title>Zapvertising</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <form className={styles.form} onSubmit={handleSubmit}>
        <input
          className={styles.input}
          placeholder="Enter npub, note ID, nevent, or naddr"
        />
        <button className={styles.button} type="submit">
          Go
        </button>
      </form>
    </>
  );
};
